apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: tmb13db1
spec:
  type: NodePort
  selector:
    app: Frontend
  ports:
    - protocol: TCP
      port: 3000    
      targetPort: 3000
      nodePort: 30087