apiVersion: v1
kind: Secret 
metadata:
  name: backend-secret
  namespace: tmb13dbe
type: Opaque
data:
  MONGO_URI: bW9uZ29kYjovL21vbmdvZGItc2VydmljZS50bWIxM2RiLnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3

  # mongodb-service.tmb13db.